version: 1.0

# cPanel Git deployment hooks for static export (npm)
# Installs dependencies with npm, builds the project, and copies the built
# output from `dist` into the site's public_html directory.

hooks:
  pre_deploy:
    - echo "Running pre-deploy tasks"
    - npm ci --prefer-offline --no-audit --progress=false

  post_deploy:
    - echo "Running build"
    - npm run build
    - echo "Copying build output to public_html"
    - mkdir -p "$HOME/public_html"
    - rm -rf "$HOME/public_html"/* || true
    - cp -R dist/. "$HOME/public_html/"
    - chmod -R 755 "$HOME/public_html"
    - echo "Deployment complete"
